API_KEY = 'PipcyZtskLcZxuOESeTi3p2WKVrlJimdjlpngTX6bODVPVZxriJ7uJlGT05s2tRd'
API_SECRET = 'fo1OFsFuJFBNQaaCTwLRfHUn4HVldnem3BQTHOx6XaHZcYCioOutHIu6NvkacJN4'
GMAIL_EMAIL = 'botfab42@gmail.com'
GMAIL_PASSWORD = '$number42Bot'