
import re
from datetime import datetime

listPrice = ['LTCBTC', 'NEOBTC', 'EOSETH', 'NEOETH', 'LINKBTC', 'LINKETH', 'EOSBTC', 'ETCETH', 'ETCBTC', 'DASHBTC', 'DASHETH', 'BNBUSDT', 'NEOUSDT', 'ADABTC', 'ADAETH', 'XLMBTC', 'XLMETH', 'LTCETH', 'LTCUSDT', 'NEBLETH', 'IOSTBTC', 'IOSTETH', 'ADAUSDT', 'TRXUSDT', 'VETBTC', 'VETETH', 'VETUSDT', 'BNBPAX', 'BNBTUSD', 'BNBUSDC', 'TRXTUSD', 'LTCUSDC', 'TRXPAX', 'TRXUSDC', 'IOSTBNB', 'IOSTUSDT', 'ATOMBTC', 'ATOMUSDT', 'ATOMUSDC', 'DOGEBTC', 'DOGEUSDT', 'BNBBUSD', 'ETCBUSD', 'TRXBUSD', 'VETBUSD', 'BTSUSDT', 'ATOMBUSD', 'MATICBUSD', 'BNBGBP', 'MKRBTC', 'MKRBUSD', 'DOGEBUSD', 'AUDBUSD', 'IOTABUSD', 'JSTBTC', 'JSTBUSD', 'JSTUSDT', 'TRXUPUSDT', 'SUNUSDT', 'BNBBRL', 'SKLBUSD', 'SKLUSDT', 'SUSDUSDT', 'COVERBUSD', 'TRXTRY', 'USDTBVND', 'USDCBUSD', 'DOGEEUR', 'DOGETRY', 'DOGEAUD', 'DOGEBRL', 'DOGEGBP', 'IOSTBUSD', 'MATICEUR', 'RVNTRY', 'THETAEUR', 'TLMBTC', 'TLMBUSD', 'TLMUSDT']
now = datetime.now()
for item in listPrice:
    if 'USDT' in str(item):
        print(F'{item} - {now}')


